// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_array.proto

#ifndef PROTOBUF_msg_5farray_2eproto__INCLUDED
#define PROTOBUF_msg_5farray_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "msg.pb.h"
// @@protoc_insertion_point(includes)
namespace proto2_proto_example {
class MessageArray;
class MessageArrayDefaultTypeInternal;
extern MessageArrayDefaultTypeInternal _MessageArray_default_instance_;
class MessageArray_MsgMapEntry;
class MessageArray_MsgMapEntryDefaultTypeInternal;
extern MessageArray_MsgMapEntryDefaultTypeInternal _MessageArray_MsgMapEntry_default_instance_;
}  // namespace proto2_proto_example

namespace proto2_proto_example {

namespace protobuf_msg_5farray_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msg_5farray_2eproto

// ===================================================================


// -------------------------------------------------------------------

class MessageArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto2_proto_example.MessageArray) */ {
 public:
  MessageArray();
  virtual ~MessageArray();

  MessageArray(const MessageArray& from);

  inline MessageArray& operator=(const MessageArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageArray(MessageArray&& from) noexcept
    : MessageArray() {
    *this = ::std::move(from);
  }

  inline MessageArray& operator=(MessageArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageArray& default_instance();

  static inline const MessageArray* internal_default_instance() {
    return reinterpret_cast<const MessageArray*>(
               &_MessageArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MessageArray* other);
  friend void swap(MessageArray& a, MessageArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageArray* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageArray& from);
  void MergeFrom(const MessageArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .proto2_proto.Message> msg_map = 1;
  int msg_map_size() const;
  void clear_msg_map();
  static const int kMsgMapFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::proto2_proto::Message >&
      msg_map() const;
  ::google::protobuf::Map< ::std::string, ::proto2_proto::Message >*
      mutable_msg_map();

  // @@protoc_insertion_point(class_scope:proto2_proto_example.MessageArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  public:
  class MessageArray_MsgMapEntry : public ::google::protobuf::internal::MapEntry<MessageArray_MsgMapEntry, 
      ::std::string, ::proto2_proto::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<MessageArray_MsgMapEntry, 
      ::std::string, ::proto2_proto::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    MessageArray_MsgMapEntry();
    MessageArray_MsgMapEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const MessageArray_MsgMapEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_MessageArray_MsgMapEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      MessageArray_MsgMapEntry,
      ::std::string, ::proto2_proto::Message,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > msg_map_;
  private:
  friend struct protobuf_msg_5farray_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MessageArray

// map<string, .proto2_proto.Message> msg_map = 1;
inline int MessageArray::msg_map_size() const {
  return msg_map_.size();
}
inline void MessageArray::clear_msg_map() {
  msg_map_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::proto2_proto::Message >&
MessageArray::msg_map() const {
  // @@protoc_insertion_point(field_map:proto2_proto_example.MessageArray.msg_map)
  return msg_map_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::proto2_proto::Message >*
MessageArray::mutable_msg_map() {
  // @@protoc_insertion_point(field_mutable_map:proto2_proto_example.MessageArray.msg_map)
  return msg_map_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto2_proto_example

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5farray_2eproto__INCLUDED
